# Generated by Django 4.0.4 on 2022-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'required': 'Faqat raqam kiriting!!!'}, max_length=13, null=True),
        ),
    ]
